import Head from 'next/head';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Amplify, API, Auth } from 'aws-amplify';

Amplify.configure({
    Auth: {
        region: 'ap-southeast-1', // REQUIRED - Amazon Cognito Region
        userPoolId: 'ap-southeast-1_4AgRv5gBm', // OPTIONAL - Amazon Cognito User Pool ID
        userPoolWebClientId: '14gvr06ljo63egbnjvhaajfgem', // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    },
    API: {
        endpoints: [
            {
                name: 'api-sls',
                endpoint: 'https://t8bud0vu4b.execute-api.ap-southeast-1.amazonaws.com/dev',
            },
        ],
    },
});

export default function Home() {
    const getUserData = async () => {
        const user = await Auth.currentAuthenticatedUser();
        const idToken = user.signInUserSession.idToken.jwtToken;
        const requestHeader = {
            headers: {
                Authorization: idToken,
            },
            body: {
                email: user.attributes.email,
                name: user.attributes.name,
                age: 18,
            },
        };
        const data = await API.post('api-sls', '/hello', requestHeader);
    };
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>HieuAWS | Serverless Tutorials</h1>
            <Authenticator
                loginMechanisms={['email']}
                signUpAttributes={['name']}
                socialProviders={['amazon', 'apple', 'facebook', 'google']}
            >
                {({ signOut, user }) => (
                    <main>
                        <h1>
                            Hello {user.attributes.name} - {user.attributes.email}
                        </h1>
                        <button onClick={getUserData}>Call API</button>
                        <br />
                        <button onClick={signOut}>Sign out</button>
                    </main>
                )}
            </Authenticator>
        </>
    );
}
